### ISSUE TITLE
"autobroadcast"

### ISSUE THREAD

**Issue by CaszGamerMD** [CaszGamerMD/NootSpeak#2]
[Auto "Noot" Cast] aka: "N3 - Nootopian News Network"
  - auto message every OnlinePlayer, message, time

AutoBroadcast - *broadcasts + links will be saved in a separate file/folder?*

*NootSpeak>AutoCast>broadcasts.yml*
in config.yml
NootCast:
--Timer: time in seconds
--CastingType: Random/Order
--Prefix:"&b[&2Noot&aCast&b]"

*broadcasts.yml*
[#]: // number of message, used if in order casting type.
--Broadcast: "Message"
--Type: None/Link/CMD
--Action: "Link/CMD/[] "  //[] for no action

**Comment by CaszGamerMD** [comment]
update: added code but its not connected to Main as of yet. no errors i think.

**Comment by Haileykins** [comment]
Changed And Repaired Broadcaster Plugin.
